---
apiVersion: v1
kind: Namespace
metadata:
  name: synergy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergy-logger
  namespace: synergy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergy
  template:
    metadata:
      labels:
        app: synergy
    spec:
      containers:
      - name: logger
        image: busybox
        command: 
        - /bin/sh
        - -c
        - |
          while true; do
            echo "$(date) - Synergy leverager is running" >> /var/log/synergy-leverager.log
            sleep 5
          done
